Repository germs-lab/interbrc-core-analysis, pull requests merged in 2025-03, with the labels that each got.

#16 NMDS stress plot
  R/005_core_physeqs_ordinations.R
  R/misc_functions.R
  data/output/plots/nmds_stressplot.png
Labels: enhancement, High Priority

#18 Updating .gitignore to ignodre .DS_* files created on Macs
  .DS_Store
  .gitignore
  tests/.DS_Store
Labels: bug

#22 Last call function refactor
  R/extract_core.R
  tests/test_analysis.R
Labels: bug

#26 Reorganize R/ Directory for Better Project Structure
  R/003_summary_stats.R
  R/analysis/001_quality_control.R
  R/analysis/002_phyloseq_import.R
  R/analysis/003_summary_stats.R
  R/analysis/004_core_analysis.R
  R/analysis/005_core_physeqs_fasta.R
  R/analysis/006_core_ordinations.R
  R/functions/extract_core.R
  R/functions/misc_functions.R
  R/functions/model_fit.R
  R/references/REF_corn_dada2-phyloseq.R
  R/references/REF_example_analysis.R
  R/references/REF_selected_ASVs_high-low.R
  R/references/dada2_template.R
  R/utils/000_setup.R
  scripts/reorganizeR.sh
Labels: documentation, enhancement

#31 Function testing: Refactor `ExtractCore()` Return List and Enhance Testing Workflow
  .Rbuildignore
  .github/.gitignore
  .github/workflows/tests.yml
  R/analysis/003_summary_stats.R
  R/analysis/004_core_analysis.R
  R/analysis/005_core_physeqs_fasta.R
  R/analysis/006_core_ordinations.R
  R/functions/calculate_bc.R
  R/functions/calculate_nmds.R
  R/functions/extract_core.R
  R/functions/filter_core.R
  R/functions/misc_functions.R
  R/functions/select_asvs.R
  R/utils/000_setup.R
  data/output/high_occ_matrix.rda
  renv.lock
  tests/testthat.R
  tests/testthat/expected_extract_core.rda
  tests/testthat/expected_nmds.rda
  tests/testthat/test-calculate_bc.R
  tests/testthat/test-calculate_nmds.R
  tests/testthat/test-extract_core.R
  tests/testthat/test-filter_core.R
Labels: bug, documentation, enhancement

#32 Gains `test-filter_core.R`. Improved error messaged in `filter_core` …
  R/functions/filter_core.R
  tests/testthat/test-filter_core.R
Labels: bug, enhancement

#33 Improvements to NMDS from threshold analysis and `multi_rarefy`
  R/analysis/006_core_ordinations.R
  R/functions/calculate_nmds.R
  R/functions/misc_functions.R
  R/functions/multi_rarefy.R
  R/utils/000_setup.R
  data/output/plots/core_nmds_brc.png
  data/output/plots/core_nmds_crops.png
  tests/test_analysis.R
Labels: enhancement, Normal Priority

#38 Patch to `utils/000_steup.R`
  R/utils/000_setup.R
Labels: bug
